# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Peter Zukerman
tagline:          ''
description:      'Languages, Progamming, and Thoughts'
url:              peterzukerman.github.io
baseurl:          /

author:
  name:           'Peter Zukerman'
  url:            https://twitter.com/peterzuker

plugins:          [jekyll-paginate, redcarpet, jekyll-gist, jekyll-avatar, jekyll-admin]
paginate:         5
paginate_path:    "page:num"
ighlighter: rouge
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/peterzukerman/peterzukerman.github.io
